/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as RotaRouteImport } from './routes/rota'
import { Route as SolicitarRouteImport } from './routes/solicitar'
import { Route as EquipamentosIndexRouteImport } from './routes/equipamentos.index'
import { Route as EquipamentosIdRouteImport } from './routes/equipamentos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RotaRoute = RotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitarRoute = SolicitarRouteImport.update({
  id: '/solicitar',
  path: '/solicitar',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosIndexRoute = EquipamentosIndexRouteImport.update({
  id: '/equipamentos/',
  path: '/equipamentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosIdRoute = EquipamentosIdRouteImport.update({
  id: '/equipamentos/$id',
  path: '/equipamentos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/notificacoes': typeof NotificacoesRoute
  '/rota': typeof RotaRoute
  '/solicitar': typeof SolicitarRoute
  '/equipamentos/$id': typeof EquipamentosIdRoute
  '/equipamentos/': typeof EquipamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/notificacoes': typeof NotificacoesRoute
  '/rota': typeof RotaRoute
  '/solicitar': typeof SolicitarRoute
  '/equipamentos/$id': typeof EquipamentosIdRoute
  '/equipamentos': typeof EquipamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/notificacoes': typeof NotificacoesRoute
  '/rota': typeof RotaRoute
  '/solicitar': typeof SolicitarRoute
  '/equipamentos/$id': typeof EquipamentosIdRoute
  '/equipamentos/': typeof EquipamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mapa'
    | '/notificacoes'
    | '/rota'
    | '/solicitar'
    | '/equipamentos/$id'
    | '/equipamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mapa'
    | '/notificacoes'
    | '/rota'
    | '/solicitar'
    | '/equipamentos/$id'
    | '/equipamentos'
  id:
    | '__root__'
    | '/'
    | '/mapa'
    | '/notificacoes'
    | '/rota'
    | '/solicitar'
    | '/equipamentos/$id'
    | '/equipamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapaRoute: typeof MapaRoute
  NotificacoesRoute: typeof NotificacoesRoute
  RotaRoute: typeof RotaRoute
  SolicitarRoute: typeof SolicitarRoute
  EquipamentosIdRoute: typeof EquipamentosIdRoute
  EquipamentosIndexRoute: typeof EquipamentosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rota': {
      id: '/rota'
      path: '/rota'
      fullPath: '/rota'
      preLoaderRoute: typeof RotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitar': {
      id: '/solicitar'
      path: '/solicitar'
      fullPath: '/solicitar'
      preLoaderRoute: typeof SolicitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos/': {
      id: '/equipamentos/'
      path: '/equipamentos'
      fullPath: '/equipamentos/'
      preLoaderRoute: typeof EquipamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos/$id': {
      id: '/equipamentos/$id'
      path: '/equipamentos/$id'
      fullPath: '/equipamentos/$id'
      preLoaderRoute: typeof EquipamentosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapaRoute: MapaRoute,
  NotificacoesRoute: NotificacoesRoute,
  RotaRoute: RotaRoute,
  SolicitarRoute: SolicitarRoute,
  EquipamentosIdRoute: EquipamentosIdRoute,
  EquipamentosIndexRoute: EquipamentosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
